### ISSUE TITLE
"Topic node" pages should be more informative

### ISSUE THREAD

**Issue by rybesh** [editorsnotes/editorsnotes#170]
e.g. http://editorsnotes.org/topics/1223/

If I came to this page via <https://www.google.com/search?q=International+Committee+Planned+Parenthood> it wouldn't be clear to me what I was looking at. 

I think topic node pages should look similar to topic pages, except that the lists of notes and documents should include items from multiple projects.

**Comment by ptgolden** [comment]
there are no more topic nodes
