### ISSUE TITLE
Project-specific "browse" pages AKA project home pages

### ISSUE THREAD

**Issue by rybesh** [editorsnotes/editorsnotes#243]
Via MKB:

If one started with http://editorsnotes.org/projects/japanese_librarianship/ and retained the large project title at the top and the project description below it on the left -- and removed the reverse chronological list of "Recent edits".
 
Then replicated the three "Recently..." sections of http://editorsnotes.org/browse/ using the same layout but with the contain limited to Japan project items, one would have an attractive and effective overview of the project and recent work on it.

The "Recent edits" list could I suppose be retained under all that but that would require scrolling down and I think that having it on a separate page with a link to it would be better design.

**Comment by ptgolden** [comment]
This issue was moved to editorsnotes/editorsnotes-renderer#11
