### ISSUE TITLE
Registration and project management workflow

### ISSUE THREAD

**Issue by ptgolden** [editorsnotes/editorsnotes#263]
We discussed this previously, and half-heartedly decided to move registration functionality out of an HTML form-based thing to the JSON API. I'm wavering about that decision a little bit.

I think it's OK to have this program (the Editors' Notes API server), serve HTML for the user/project registration/management workflow. It makes everything so much easier, and probably makes a lot more sense.

This HTML in this section could potentially look "different" than the main site to some extent, because I don't want to duplicate the code from the other repo to here. This is also OK, in my opinion. Editing this stuff should be rare and not normal, and a change in the interface would reflect that.

**Comment by rybesh** [comment]
> I think it's OK to have this program (the Editors' Notes API server), serve HTML for the user/project registration/management workflow. It makes everything so much easier, and probably makes a lot more sense.

I'm cool with that.

**Comment by ptgolden** [comment]
I'm marking this as closed, because the basic workflow is implemented. Let's file more specific issues for missing things.
